version: "2"

services:
  monet-api:
    build: "."
    image: "toksaitov/monet-api"
    volumes:
      - ".:/monet-api"
    ports:
      - "8080:8080"
    depends_on:
      - "monet-redis-db"
      - "monet-mongo-db"

  monet-redis-db:
    image: "redis:3.0.7"
    networks:
      default:
        aliases:
          - "monet-queue-db"
  monet-mongo-db:
    image: "mongo:3.2.6"
    networks:
      default:
        aliases:
          - "monet-task-db"
          - "monet-artwork-db"
